# Generated by Django 6.0.6 on 2026-06-15 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BREAKFAST', 'Breakfast Profile'), ('LUNCH', 'Lunch Profile'), ('DINNER', 'Supper/Dinner Profile'), ('DRINK', 'Soft Drinks Profile')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(max_length=30, unique=True)),
                ('rank', models.CharField(choices=[('2LT', 'Second Lieutenant'), ('LT', 'Lieutenant'), ('CAPT', 'Captain'), ('MAJ', 'Major'), ('LT_COL', 'Lieutenant Colonel'), ('COL', 'Colonel'), ('BRIG', 'Brigadier'), ('MAJ_GEN', 'Major General'), ('LT_GEN', 'Lieutenant General'), ('GEN', 'General')], max_length=10)),
                ('office_location', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACCEPTED', 'Accepted by Mess Admin'), ('CANCELLED', 'Cancelled by Officer')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='orders.menuitem')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.officerprofile')),
            ],
        ),
    ]
